<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>multiple test points - Create and update a task by both API and UI</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bc43039c-fa0b-4378-80b4-8222520a7fce</testSuiteGuid>
   <testCaseLink>
      <guid>c9c7027c-4e2b-472a-af26-0e9ad49dbc55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Create and update a ticket by both API and UI</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64bd85d7-7795-4cb6-a05b-3bf26fb66127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6dc30f6-4ea0-45b5-89de-e05adf9add85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f0a04e2-9584-4019-aa84-5dc9f837e1d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33b33e69-742d-471f-9454-ccdf4dfdb5d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36885381-1421-4997-be38-b0415a911725</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recording</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
