name: KS Regression Automation

trigger:
  - master

pool:
  name: Default
  demands:
    - agent.name -equals Truyens-MacBook-Air-2

jobs:
- job: Test
  steps:
  - script: |
      echo "Hello, World!"
    displayName: 'Run a one-line script'
