name: KS Regression Automation

trigger:
  - master

pool:
  name: Default
  demands:
    - agent.name -equals Truyens-MacBook-Air-2

jobs:
- job: Test
  steps:
  - script: |
      echo "Hello, World!"
    displayName: 'Run a one-line script'
  - bash: |
      echo "Downloading KRE package..."
      curl "https://download.katalon.com/${VERSION}/Katalon_Studio_Engine_MacOS-${VERSION}.tar.gz" -o katalon_runtime_engine.tar.gz
    displayName: 'Download KRE package'
  - bash: |
      echo "Unzipping KRE package..."
      tar -xvf katalon_runtime_engine.tar.gz
    displayName: 'Unzip KRE package'
  - script: |
      set -ex
      kataloncPath="$(pwd)/Katalon_Studio_Engine_MacOS-${VERSION}/Katalon Studio Engine.app/Contents/MacOS/katalonc"
      projectPath="${WORK_DIR}/Sample-Jira-ticket-creation.prj"
      testSuite="${WORK_DIR}/Test Suites"
      echo "Project path: $projectPath"
      echo "Katalon path: $kataloncPath"
      echo "Test suite path: $testSuite"
      ls -al "$(pwd)"
      ls -al "$projectPath"
      cd "$testSuite"
      ls -al
      "$kataloncPath" -apiKey="fb1d50ee-4fb5-4fee-b9af-c155a9e7b151" -projectPath="$projectPath" -testSuitePath="Test Suites/multiple test points - Create and update a task by both API and UI" -browserType="Firefox (headless)" --config -webui.autoUpdateDrivers=${AUTO_UPDATE_WEBDRIVERS}
    displayName: 'Run sample WebUI and API combination test'
