
## this configuration is ignored since the pipeline is already connected to github
## and there is already a step checkout to clone script from github under 'steps'
# resources: 
#   repositories:
  # - repository: WebUIKeywordsTest
  #   type: github
  #   ref: refs/heads/master
  #   name: katalon-studio-samples/web-samples
  #   endpoint: github.com_kms-loantran

trigger:
  - master

pool:
  name: Default
  demands:
   - agent.Name -equals Truyens-MacBook-Air-2

stages:
- stage: Test
  displayName: Run Automation script
  jobs:
  - job: TestOnMac
    displayName: Run automation script on Mac
    continueOnError: true
    variables:  # job-level
      VERSION: '8.2.0'
      AUTO_UPDATE_WEBDRIVERS: true
      WORK_DIR: $(Build.Repository.LocalPath)
      TMP_DIR: $(Build.ArtifactStagingDirectory)
    steps:
    - checkout: self
      clean: true
      fetchDepth: 1
    - bash: |
        set -ex
        curl "https://download.katalon.com/${VERSION}/Katalon_Studio_Engine_MacOS-${VERSION}.tar.gz" -o katalon_runtime_engine.tar.gz
      displayName: download KRE package
    - bash: |
        set -ex
        tar -xvf katalon_runtime_engine.tar.gz
      displayName: unzip KRE package
    - script: |
        set -ex
        kataloncPath="$(pwd)/Katalon_Studio_Engine_MacOS-${VERSION}/Katalon Studio Engine.app/Contents/MacOS/katalonc"
        projectPath="${WORK_DIR}/Sample-Jira-ticket-creation.prj"
        testSuite="${WORK_DIR}/Test Suites"
        ls -al
        echo $projectPath
        echo $katalonc
        echo $testSuite
        ls -al "$(pwd)/Sample-Jira-ticket-creation.prj"
        cd '/Users/truyen.nguyen/myagent/_work/1/s/Test Suites'
        ls -al
        "$kataloncPath" -apiKey="5e688284-405a-42d1-a07a-1a68cec8422d" -projectPath="$projectPath" -testSuitePath="Test Suites/multiple test points - Create and update a task by both API and UI" -browserType="Chrome (headless)" --config -webui.autoUpdateDrivers=${AUTO_UPDATE_WEBDRIVERS}
      displayName: Run sample WebUI and API combination test